// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent to polish resume descriptions based on the target position.
 *
 * - polishResumeDescription - A function that handles the resume polishing process.
 * - PolishResumeDescriptionInput - The input type for the polishResumeDescription function.
 * - PolishResumeDescriptionOutput - The return type for the polishResumeDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PolishResumeDescriptionInputSchema = z.object({
  sectionDescription: z
    .string()
    .describe('The description of the resume section to be polished.'),
  targetPosition: z
    .string()
    .describe('The type of position the user is applying for.'),
});
export type PolishResumeDescriptionInput = z.infer<
  typeof PolishResumeDescriptionInputSchema
>;

const PolishResumeDescriptionOutputSchema = z.object({
  polishedDescription: z
    .string()
    .describe('The polished description for the resume section.'),
});
export type PolishResumeDescriptionOutput = z.infer<
  typeof PolishResumeDescriptionOutputSchema
>;

export async function polishResumeDescription(
  input: PolishResumeDescriptionInput
): Promise<PolishResumeDescriptionOutput> {
  return polishResumeDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'polishResumeDescriptionPrompt',
  input: {schema: PolishResumeDescriptionInputSchema},
  output: {schema: PolishResumeDescriptionOutputSchema},
  prompt: `You are a professional resume writer. Your task is to polish the provided resume section description so that it is appropriate for the specified target position.  Make sure to only rewrite the description, without any additional text.

Section Description: {{{sectionDescription}}}
Target Position: {{{targetPosition}}}`,
});

const polishResumeDescriptionFlow = ai.defineFlow(
  {
    name: 'polishResumeDescriptionFlow',
    inputSchema: PolishResumeDescriptionInputSchema,
    outputSchema: PolishResumeDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
